export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_SENT: '/reset-password-sent',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_SUCCESS: '/verify-email/success',
  VERIFY_EMAIL_FAILED: '/verify-email/failed',
  RESEND_VERIFICATION: '/resend-verification',
  CHANGE_PASSWORD: '/change-password',
  DASHBOARD: '/dashboard',
  HOME: '/',
  JOBS: '/jobs',
  COMPANIES: '/companies',
  ABOUT: '/about',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};
